# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'GJCUBarScanner' do

pod 'ZXingObjC','~> 3.0'

end

target 'GJCUBarScannerTests' do

end

